### ISSUE TITLE
How do I use playwright-test-coverage in a Vite Project?

### ISSUE THREAD

**Issue by knightcube** [anishkny/playwright-test-coverage#148]
This is the project that I am working on - https://github.com/knightcube/open-bus-map-search

I have added some tests in the `tests/` folder and would like to know how to generate a code coverage report using `playwright-test-coverage`.

I tried following [this blog post](https://dev.to/anishkny/code-coverage-for-a-nextjs-app-using-playwright-tests-18n7) but it is only for Next.js projects. 

However, I need to generate the code coverage report for a project that uses Vite, React, and TypeScript.

Could you please tell me what steps need to be followed in order to do so?

**Comment by anishkny** [comment]
@knightcube thanks for reaching out. Yes the blog shows only Next.js because there are too many frameworks out there to demo all.

Did you try using [`vite-plugin-istanbul`](https://www.npmjs.com/package/vite-plugin-istanbul) to instrument your code using `instanbul`, and then run Playwright tests to generate coverage? That should work.
